language: python
python:
  - 3.6
cache:
  - pip
script:
  - pip install -r requirements.txt pytest flake8

  # run linter
  - flake8

  # run the worker tests (docker utilities for now)
  - pytest -v workers

  # check the buildbot configuration
  - pip install buildbot
  - buildbot checkconfig
